main: ik.kvlzx.org.IntKnock
version: 6.2.5
name: ik
author: Kvlzx
api-version: 1.13


commands:
  IntKnock:
    description: Comando principal de IntKnock
    aliases:
    - ik
    - IntK
    - IKnock
    - IK

  Report:
    description: Comando para reportar usuarios
    aliases:
    - report
    - rept
