main: kk.kvlzx.KvKnockback
version: 1.0.0-SNAPSHOT
name: KvKnockback
authors: [Kvlzx, Gabo]
api-version: 1.13
depend: [WorldEdit, TAB]

commands:
  kvknockback:
    description: Main command
    aliases: 
      - kvk
      - kk
  report:
    description: Command to report a player
  arena:
    description: Command to define an arena
  stats:
    description: Command to manage statistics
    aliases: [statistics]