main: mk.kvlzx.MysthicKnockBack
version: 1.0.0-SNAPSHOT
name: MysthicKnockBack
authors: [Kvlzx, Gabo]
api-version: 1.13
depends: [WorldEdit]

commands:
  mysthicknockback:
    description: Main command
    aliases: 
      - mk
      - kb
      - kbffa
  report:
    description: Command to report a player
  arena:
    description: Command to define an arena
  stats:
    description: Command to manage statistics
    aliases: [statistics]
  music:
    description: Open the music menu
  friend:
    description: Command to manage your friends list
  msg:
    description: Command to send a message to another player
    aliases: [message, tell]
  r:
    description: Command to reply to the last private message received
    aliases: [reply]
  ignore:
    description: Command to manage ignored players