chat:
  chat:
  # Enable or disable the custom chat system
  enabled: true
  
  # Default format if no specific group format is found
  # Available placeholders:
  # %player_name% - Player's name
  # %message% - Player's message
  # %kbffa_rank% - Player's elo rank
  # Also supports PlaceholderAPI placeholders if installed
  default-format: "%kbffa_rank% &7%player_name%&7: &f%message%"
  
  # Specific formats for LuckPerms groups
  # The group name must EXACTLY match the name in LuckPerms
  # If a player belongs to a group listed here, this format will be used
  # Otherwise, it will use the default-format above
  group-formats:
    
    # Owner
    owner: "&4&l[OWNER] &c%player_name%&7: &f%message%"
    
    # Admin
    admin: "&c&l[ADMIN] &4%player_name%&7: &f%message%"
    
    # Moderator
    moderator: "&9&l[MOD] &b%player_name%&7: &f%message%"
    mod: "&9&l[MOD] &b%player_name%&7: &f%message%"
    
    # Helper
    helper: "&a&l[HELPER] &2%player_name%&7: &f%message%"
    
    # Developer
    developer: "&3&l[DEV] &b%player_name%&7: &f%message%"
    dev: "&3&l[DEV] &b%player_name%&7: &f%message%"
    
    # Builder
    builder: "&2&l[BUILDER] &a%player_name%&7: &f%message%"
    
    # VIP
    vip: "&6&l[VIP] &e%player_name%&7: &f%message%"
    
    # VIP+
    vipplus: "&6&l[VIP&b+&6] &e%player_name%&7: &f%message%"
    vip_plus: "&6&l[VIP&b+&6] &e%player_name%&7: &f%message%"
    
    # Premium
    premium: "&d&l[PREMIUM] &5%player_name%&7: &f%message%"
    
    # YouTuber
    youtuber: "&f&l[&cYou&fTuber&f] &c%player_name%&7: &f%message%"
    youtube: "&f&l[&cYou&fTuber&f] &c%player_name%&7: &f%message%"
    
    # Streamer
    streamer: "&5&l[STREAMER] &d%player_name%&7: &f%message%"
    
    # Influencer
    influencer: "&e&l[INFLUENCER] &6%player_name%&7: &f%message%"
    
    # Partner
    partner: "&d&l[PARTNER] &5%player_name%&7: &f%message%"
    
    # Default
    default: "%kbffa_rank% &7%player_name%&7: &f%message%"

tab:
  # Enable or disable the tab formatting system
  enabled: true
  
  # Default format if no specific group format is found
  # Available placeholders:
  # %player_name% - Player's name
  # %kbffa_rank% - Player's elo rank
  # %player_ping% - Player's ping
  # Also supports PlaceholderAPI placeholders if installed
  default-format: "%kbffa_rank% &f%player_name% &8[&f%player_ping%ms&8]"
  default-display-name: "%kbffa_rank% &f%player_name%"
  
  # Specific formats for LuckPerms groups
  # The group name must EXACTLY match the name in LuckPerms
  # If a player belongs to a group listed here, this format will be used
  # Otherwise, it will use the default-format above
  # The order of the groups is important, as it will be the order in which they are displayed in the tab (priority)
  group-formats:
    
    # Owner
    owner:
      tab-format: "&4&l[OWNER] &c%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&4&l[OWNER] &c%player_name%"
    
    # Admin
    admin:
      tab-format: "&c&l[ADMIN] &4%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&c&l[ADMIN] &4%player_name%"
    
    # Moderator
    moderator:
      tab-format: "&9&l[MOD] &b%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&9&l[MOD] &b%player_name%"
    mod:
      tab-format: "&9&l[MOD] &b%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&9&l[MOD] &b%player_name%"
    
    # Helper
    helper:
      tab-format: "&a&l[HELPER] &2%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&a&l[HELPER] &2%player_name%"
    
    # Developer
    developer:
      tab-format: "&3&l[DEV] &b%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&3&l[DEV] &b%player_name%"
    dev:
      tab-format: "&3&l[DEV] &b%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&3&l[DEV] &b%player_name%"
    
    # Builder
    builder:
      tab-format: "&2&l[BUILDER] &a%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&2&l[BUILDER] &a%player_name%"
    
    # VIP
    vip:
      tab-format: "&6&l[VIP] &e%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&6&l[VIP] &e%player_name%"
    
    # VIP+
    vipplus:
      tab-format: "&6&l[VIP&b+&6] &e%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&6&l[VIP&b+&6] &e%player_name%"
    vip_plus:
      tab-format: "&6&l[VIP&b+&6] &e%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&6&l[VIP&b+&6] &e%player_name%"
    
    # Premium
    premium:
      tab-format: "&d&l[PREMIUM] &5%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&d&l[PREMIUM] &5%player_name%"
    
    # YouTuber
    youtuber:
      tab-format: "&f&l[&cYou&fTuber&f] &c%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&f&l[&cYou&fTuber&f] &c%player_name%"
    youtube:
      tab-format: "&f&l[&cYou&fTuber&f] &c%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&f&l[&cYou&fTuber&f] &c%player_name%"
    
    # Streamer
    streamer:
      tab-format: "&5&l[STREAMER] &d%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&5&l[STREAMER] &d%player_name%"
    
    # Influencer
    influencer:
      tab-format: "&e&l[INFLUENCER] &6%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&e&l[INFLUENCER] &6%player_name%"
    
    # Partner
    partner:
      tab-format: "&d&l[PARTNER] &5%player_name% &8[&f%player_ping%ms&8]"
      display-name: "&d&l[PARTNER] &5%player_name%"
    
    # Default
    default:
      tab-format: "%kbffa_rank% &f%player_name% &8[&f%player_ping%ms&8]"
      display-name: "%kbffa_rank% &f%player_name%"

join-messages:
  enabled: true
  
  # Custom messages for LuckPerms groups when a player joins
  # If a player belongs to a group listed here, this message will be used
  # Otherwise, it will use the default join message
  group-messages:
    owner: "&8[&a+&8] &c&lOWNER &f%player_name% &7has joined the server!"
    admin: "&8[&a+&8] &4&lADMIN &f%player_name% &7has joined the server!"
    mod: "&8[&a+&8] &6&lMOD &f%player_name% &7has joined the server!"
    vip: "&8[&a+&8] &b&lVIP &f%player_name% &7has joined the server!"
    # No specific message for 'default' group, it will use the default join message

# ================================
# IMPORTANT NOTES:
# ================================
# 1. Group names must exactly match LuckPerms
# 2. Use &f at the end of the format to reset the message color
# 3. Available colors: &0-&9, &a-&f
# 4. Available styles: &l (bold), &m (strikethrough), &n (underline), &o (italic), &k (obfuscated)
# 5. Use &r to reset all formats
# 6. If LuckPerms is not installed, everyone will use the 'default' format
# 7. The order in the tab will be the same as the order in the configuration
# 8. tab-format: How it is displayed in the tab list
# 9. display-name: How the name is displayed above the player's head
# 10. Reload the configuration with: /kb reload
# ================================