config:
  prefix: "&b[&3KBFFA&b] "
  auto-save-interval: 5 # Minutes
  endermite:
    enabled: true
    limit: 3 # Maximum number of endermites per player
    name: "&e %player%'s Pet &7(%seconds%s)"
    time: 30 # Seconds before the endermite despawns
    messages:
      spawn: "&aYou have spawned an endermite pet!"
      limit: "&cYou already have the maximum allowed endermites (%limit%)!"
  items:
    spawn-items:
      skull:
        name: "&a✦ Main Menu"
        lore: "&7Right click to open the menu"
        slot: 4
  blocks: 
    time: 5 # Seconds to despawn
  hotbar:
    default:
      items:
        knocker:
          id: STICK
          name: "&5Knocker"
          lore: "&8 It's not the strength, it's the technique."
          knockback:
            enabled: true # Item has knockback
            level: 1
        blocks:
          id: SANDSTONE
          name: "&3Sandstone"
          lore: "&8 A desert classic"
          knockback:
            enabled: false # Item does not have knockback
        bow:
          id: BOW
          name: "&bBow"
          lore: "&7Right Click to shoot an arrow"
          knockback:
            enabled: true # Item has knockback
            level: 2
        plate:
          id: GOLD_PLATE
          name: "&6Plate"
          lore: "&8 Ready to fly? Step on it and see."
          knockback:
            enabled: false # Item does not have knockback
        feather:
          id: FEATHER
          name: "&eFeather"
          lore: "&8 It's not magic, it's pure aerodynamics."
          knockback:
            enabled: false # Item does not have knockback
        pearl:
          id: ENDER_PEARL
          name: "&5Pearl"
          lore: "&8 Each throw rewrites your destiny."
          knockback:
            enabled: false # Item does not have knockback
        arrow:
          id: ARROW
          name: "&5Arrow"
          lore: null # No lore for the arrow
          knockback:
            enabled: false # Item does not have knockback
        slime_ball:
          id: SLIME_BALL
          name: "&aSlime Ball"
          lore: "&7Launch a snow balls"
          knockback:
            enabled: false # Item does not have knockback
        
  combat:
    default-elo: 500
    combat-log: 10000 # Milliseconds (10 seconds)
    speed: 0.4 # Speed of the feather (0.2 default value)
    elo:
      min: 6
      max: 15
      message-enabled: true
      message: "&a+%elo% ELO"
      death-elo-lost:
        min: 6
        max: 15
        message-enabled: true
        message: "&c-%elo% ELO"
    kgcoins:
      min: 4
      max: 12
      message-enabled: true
      message: "&a+%coins% KGCoins"
    knockback-hit:
      horizontal-knockback: 0.5
      vertical-knockback: 0.385
      knockback-resistance-reduction: 0.5
      sprint-multiplier: 1.8
    knockback-arrow:
      horizontal-knockback: 2.2
      sprint-multiplier: 2.2
    knockback-endermite:
      horizontal-knockback: 1.2
      vertical-knockback: 0.45
      knockback-level: 2
    knockback-limits:
      max-horizontal-knockback: 1.7
      max-horizontal-knockback-arrow: 2.4
      max-vertical-knockback: 0.7
    ranks:
      divine:
        display: "&d&l[Divine]"
        elo: 30500
      grand_master:
        display: "&4&l[Grand Master]"
        elo: 25500
      god:
        display: "&b&l[God]"
        elo: 20500
      titan:
        display: "&6&l[Titan]"
        elo: 18500
      immortal:
        display: "&5&l[Immortal]"
        elo: 16500
      supreme:
        display: "&c&l[Supreme]"
        elo: 14500
      mythic:
        display: "&6&l[Mythic]"
        elo: 12500
      legend:
        display: "&e&l[Legend]"
        elo: 9500
      hero:
        display: "&a&l[Hero]"
        elo: 8500
      champion:
        display: "&2&l[Champion]"
        elo: 7500
      master:
        display: "&9&l[Master]"
        elo: 6500
      elite:
        display: "&1&l[Elite]"
        elo: 5500
      veteran:
        display: "&8&l[Veteran]"
        elo: 4500
      competitor:
        display: "&7&l[Competitor]"
        elo: 3500
      apprentice:
        display: "&f&l[Apprentice]"
        elo: 2000
      novice:
        display: "&7[Novice]"
        elo: 1000
      random:
        display: "&8[Random]"
        elo: 500
  titles:
    join-title:
      enabled: true
      title: "&a Welcome to &6KnockbackFFA&a!"
      subtitle: "&fDominate the arena and leave your mark!."
      fade-in: 20 # Ticks
      stay: 60 # Ticks
      fade-out: 20 # Ticks
  music:
    limit: 30 # Maximum blocks the player can move away from the jukebox
    messages:
      non-space-preview: "&cThere is no space for the music preview."
      non-space: "&cThere is not enough space to place the jukebox."
      jukebox-error: "&cError placing the jukebox."
      move-too-far: "&cYou have moved too far from your jukebox."
  report:
    cooldown: 120000 # Milliseconds (2 minutes)
    messages:
      cooldown: "&cYou must wait %time% seconds to report this player."
      report-message: "&aReport %target% for %reason% send successfully!"
      report-message-staff: "&c[Report] &f%reporter% &7has reported &f%target% &7for &f%reason%"
  powerups:
    pickup-radius: 1.8
    time: 30 # Seconds
    spawn-interval: 25 # Seconds
    max-powerups: 4 # Max powerups per arena
    min-distance: 4.0 # Min distance between powerups
    powerups:
      jump-1:
        id: RABBIT_FOOT
        name: "&aJump I"
        lore:
          - "&7Increases your jump"
          - "&7Level I for 20 seconds"
        effect:
          id: JUMP
          level: 0
          duration: 20 # Seconds
      jump-2:
        id: RABBIT_FOOT
        name: "&aJump II"
        lore:
          - "&7Increases your jump"
          - "&7Level II for 15 seconds"
        effect:
          id: JUMP
          level: 1
          duration: 15 # Seconds
      jump-3:
        id: RABBIT_FOOT
        name: "&aJump III"
        lore:
          - "&7Increases your jump"
          - "&7Level III for 10 seconds"
        effect:
          id: JUMP
          level: 2
          duration: 10 # Seconds
      jump-4:
        id: RABBIT_FOOT
        name: "&aJump IV"
        lore:
          - "&7Increases your jump"
          - "&7Level IV for 5 seconds"
        effect:
          id: JUMP
          level: 3
          duration: 5 # Seconds
      invisibility:
        id: FERMENTED_SPIDER_EYE
        name: "&8Invisibility"
        lore:
          - "&7Makes you invisible"
          - "&7for 5 seconds"
        effect:
          id: INVISIBILITY
          level: 0
          duration: 5 # Seconds
      knockback:
        id: STICK
        name: "&6Knockback"
        lore:
          - "&7Increases your knockback"
          - "&7for 10 seconds"
        effect:
          duration: 10 # Seconds
          multiplier: 2.0 # Knockback multiplier
      explosive-arrow:
        id: TNT
        name: "&cExplosive Arrow"
        lore:
          - "&7Grants an arrow that explodes"
          - "&7on impact, knocking back players."
        effect:
          duration: 15 # Seconds this powerup is active
          radius: 5.0 # Explosion radius
          power: 10.5 # Knockback power
      black-hole:
        id: OBSIDIAN
        name: "&5&lBlack Hole"
        lore:
          - "&7Throw a black hole that attracts"
          - "&7enemies and then repels them"
          - "&dCosmic power!"
        item:
          id: OBSIDIAN
          name: "&5&lBlack Hole Orb"
          lore:
            - "&7Right click to throw"
            - "&7Creates a devastating black hole"
            - "&dUse it wisely!"
        effect:
          max-throw-distance: 30
          attraction-radius: 10.0
          attraction-force: 1.15
          attraction-duration: 5
          repulsion-force: 2.5
          repulsion-duration: 2
      double-pearl:
        id: ENDER_PEARL
        name: "&b&lDouble Pearl"
        lore:
          - "&7Doubles the pearls obtained"
          - "&7from kills for 15 seconds"
          - "&aKill more to get more pearls!"
        effect:
          duration: 15 # Seconds
    messages:
      appeared: "&eA %powerup% &epowerup has appeared in the arena!"
      pickup: "&aYou have picked up a %powerup% &apowerup!"
      black-hole-item-pickup: "&5You have obtained a Black Hole Orb! Right click to throw."
      double-pearl-activation: "&aDouble pearl activated! +1 extra pearl per kill"
      double-pearl-expired: "&cThe double pearl effect has expired!"
  streak:
    tags:
      kill-40:
        tag: "&7MVP"
      kill-60:
        tag: "&dMVP"
      kill-80:
        tag: "&9MVP"
      kill-100:
        tag: "&aMVP"
      kill-150:
        tag: "&bMVP"
      kill-200:
        tag: "&eMVP"
      kill-250:
        tag: "&6MVP"
      kill-300:
        tag: "&cMVP"
      kill-500:
        tag: "&5MVP+"
    armor-stand:
      name: "%tag% &7- Kills: %kills%"
      location:
        location-x: 0
        location-y: 2.2
        location-z: 0
    messages:
      streak-reached: "&e%player% &fhas reached a streak of &a%streak% &akills!"
      streak-lost: "&c☠ &f%player% &7lost their streak of &c%streak% &7kills! &c☠"
    title:
      enabled: true
      title: "%rank% &f%player%"
      subtitle: "&7Streak of &f%streak% &7kills!"
      fade-in: 10
      stay: 40
      fade-out: 10
