messages:
  commands:
    main:
      reload: "&aConfiguration reloaded successfully."
      no-permission: "&cYou do not have permission to use this command."
      help:
        - "--------&r &b&lCommands MysthicKnockBack &8&m--------"
        - "/kb pet"
        - "/kb reload"
        - "/arena create <name>"
        - "/arena setzone <arena> <zoneType>"
        - "/arena setborder <arena> <size>"
        - "/arena setspawn <arena>"
        - "/arena delete <arena>"
        - "/stats"
        - "/stats <player>"
        - "/stats set <player> <stat> <value>"
        - "/stats add <player> <stat> <value>"
        - "/stats remove <player> <stat> <value>"
        - "/stats reset <player>"
        - "/stats resetall"
        - "/music"
        - "/report"
        - "--------&r &b&lCommands MysthicKnockBack &8&m--------"
    arena:
      create:
        create: "&aArena %arena% created successfully."
        already-exist: "&cThe arena already exists."
      zone:
        action:
          updated: "updated"
          set: "set"
        usage: "&cUsage: /arena setzone <arena> <spawn/pvp/void>"
        invalid-zone: "&cInvalid zone type. Use: spawn, pvp or void"
        successfully: "&aZone %zone_type% %action% for arena %arena%"
        error: "&cError setting zone. Make sure you have a valid selection."
      setspawn:
        successfully: "&aSpawn point set for arena %arena%"
        error: "&cThe arena does not exist."
      delete:
        successfully: "&aArena %arena% deleted successfully."
        error: "&cThe arena does not exist."
      setborder:
        usage: "&cUsage: /arena setborder <arena> <size>"
        error-size: "&cSize must be greater than 0."
        successfully: "&aBorder set for arena %arena%"
        error: "&cThe arena does not exist."
        number-error: "&cSize must be a valid number."
      help-message:
        - "&b=== Arena Commands ==="
        - "&f/arena create <name> &7- Creates a new arena"
        - "&f/arena setzone <arena> <spawn/pvp/void> &7- Sets/updates a zone"
        - "&f/arena setspawn <arena> &7- Sets the spawn point"
        - "&f/arena delete <arena> &7- Deletes an arena"
        - "&f/arena setborder <arena> <size> &7- Sets the arena border"
    stats:
      usage: "&cUsage: /stats [player]"
      not-found: "&cPlayer not found."
      reset: "&aStats reset for %player%."
      resetall: "&aAll stats have been reset."
      set: "&a%stat% set to %value% for %player%."
      add: "&a%value% %stat% added to %player%."
      remove: "&a%value% %stat% removed from %player%."
      invalid-stat: "&cInvalid stat. Use: elo, kills, deaths, coins."
      invalid-value: "&cInvalid value. Must be a number."
      no-permission: "&cYou do not have permission to use this command."
      amount-error: "&cAmount must be a valid number."
      admin-usage: "&cUsage: /stats <set/add/remove> <elo/kills/deaths/coins> <player> <amount>"
      reset-success: "&a%player%'s statistics have been reset."
      resetall-success: "&aAll players' statistics have been reset."
      stat-updated: "&aYou have %operation% %amount% %stat% to %player%."
      format:
        - "&8⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
        - "&b%player%'s Statistics"
        - "&7Rank: %rank%"
        - "&7ELO: &6%elo%"
        - "&7Kills: &a%kills%"
        - "&7Deaths: &c%deaths%"
        - "&7KDR: &b%kdr%"
        - "&7Current Streak: &d%current_streak%"
        - "&7Best Streak: &d%max_streak%"
        - "&7Play Time: &e%playtime%"
        - "&7KGCoins: &e%kgcoins%"
        - "&8⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"