messages:
  commands:
    main:
      reload: "&aConfiguration reloaded successfully."
      no-permission: "&cYou do not have permission to use this command."
      help:
        - "--------&r &b&lCommands MysthicKnockBack &8&m--------"
        - "/kb pet"
        - "/kb reload"
        - "/arena create <name>"
        - "/arena setzone <arena> <zoneType>"
        - "/arena setborder <arena> <size>"
        - "/arena setspawn <arena>"
        - "/arena delete <arena>"
        - "/stats"
        - "/stats <player>"
        - "/stats set <player> <stat> <value>"
        - "/stats add <player> <stat> <value>"
        - "/stats remove <player> <stat> <value>"
        - "/stats reset <player>"
        - "/stats resetall"
        - "/music"
        - "/report"
        - "--------&r &b&lCommands MysthicKnockBack &8&m--------"
    arena:
      create:
        create: "&aArena %arena% created successfully."
        already-exist: "&cThe arena already exists."
      zone:
        action:
          updated: "updated"
          set: "set"
        usage: "&cUsage: /arena setzone <arena> <spawn/pvp/void>"
        invalid-zone: "&cInvalid zone type. Use: spawn, pvp or void"
        successfully: "&aZone %zone_type% %action% for arena %arena%"
        error: "&cError setting zone. Make sure you have a valid selection."
      setspawn:
        successfully: "&aSpawn point set for arena %arena%"
        error: "&cThe arena does not exist."
      delete:
        successfully: "&aArena %arena% deleted successfully."
        error: "&cThe arena does not exist."
      setborder:
        usage: "&cUsage: /arena setborder <arena> <size>"
        error-size: "&cSize must be greater than 0."
        successfully: "&aBorder set for arena %arena%"
        error: "&cThe arena does not exist."
        number-error: "&cSize must be a valid number."
      help-message:
        - "&b=== Arena Commands ==="
        - "&f/arena create <name> &7- Creates a new arena"
        - "&f/arena setzone <arena> <spawn/pvp/void> &7- Sets/updates a zone"
        - "&f/arena setspawn <arena> &7- Sets the spawn point"
        - "&f/arena delete <arena> &7- Deletes an arena"
        - "&f/arena setborder <arena> <size> &7- Sets the arena border"
    stats:
      usage: "&cUsage: /stats [player]"
      not-found: "&cPlayer not found."
      reset: "&aStats reset for %player%."
      resetall: "&aAll stats have been reset."
      set: "&a%stat% set to %value% for %player%."
      add: "&a%value% %stat% added to %player%."
      remove: "&a%value% %stat% removed from %player%."
      invalid-stat: "&cInvalid stat. Use: elo, kills, deaths, coins."
      invalid-value: "&cInvalid value. Must be a number."
      no-permission: "&cYou do not have permission to use this command."
      amount-error: "&cAmount must be a valid number."
      admin-usage: "&cUsage: /stats <set/add/remove> <elo/kills/deaths/coins> <player> <amount>"
      reset-success: "&a%player%'s statistics have been reset."
      resetall-success: "&aAll players' statistics have been reset."
      stat-updated: "&aYou have %operation% %amount% %stat% to %player%."
      format:
        - "&8⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
        - "&b%player%'s Statistics"
        - "&7Rank: %rank%"
        - "&7ELO: &6%elo%"
        - "&7Kills: &a%kills%"
        - "&7Deaths: &c%deaths%"
        - "&7KDR: &b%kdr%"
        - "&7Current Streak: &d%current_streak%"
        - "&7Best Streak: &d%max_streak%"
        - "&7Play Time: &e%playtime%"
        - "&7KGCoins: &e%kgcoins%"
        - "&8⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
  join-messages:
    - "&e¡Watch out! &b%player% &ehas entered the server."
    - "&6%player% &ahas arrived to conquer the world."
    - "&c¡Alert! &f%player% &chas joined the chaos."
    - "&a%player% &bhas appeared with style on the server."
    - "&d¡Welcome, %player%! &5Let the adventure begin."
    - "&f%player% &7has connected stealthily..."
    - "&b%player% &3has landed from another dimension."
    - "&e¡%player% &6has entered with a legendary aura!"
    - "&c%player% &4is here to break blocks and hearts."
    - "&a¡Everyone greet %player%! &2New hero on the server."
    - "&b%player% &9has joined the epic battle."
    - "&d%player% &5brings magic and chaos to the server."
    - "&f¡%player% &ehas arrived to build their destiny!"
    - "&6¡Attention! &c%player% &6is ready to dominate."
    - "&a%player% &2has joined the green side of the server."
    - "&b¡%player% &3has entered with an enchanted pickaxe!"
    - "&e%player% &7whispers: 'Time to mine...'."
    - "&c¡Danger! &f%player% &cis here to cause trouble."
    - "&d%player% &bhas arrived with an elytra and big dreams."
    - "&a¡%player% &eis ready to explore the infinite!"
  death-messages:
    - "&b%s &fslipped on a banana peel. &aHow clumsy!"
    - "&b%s &finvented trying to fly, but forgot their wings."
    - "&b%s &ffell into the void shouting &a'I'll be back!'"
    - "&b%s &fwas tricked by a mirage and crashed."
    - "&b%s &fwanted to dance on the edge and... &aouch! &fTo the ground."
    - "&b%s &fthought they were immortal. &aSpoiler: ðey weren't."
    - "&b%s &ftripped over their own ego."
    - "&b%s &fwas defeated by gravity, their worst enemy."
    - "&b%s &finvented an epic trick and ended up on the ground."
    - "&b%s &fgot distracted watching a kitten and &a goodbye!"
    - "&b%s &fbelieved they could run faster than the wind. &aNop."
    - "&b%s &ffell, just like their Wi-Fi in the middle of a match."
    - "&b%s &fwanted to be a hero, but physics said &a'nope'."
    - "&b%s &fjumped into the void with &atoo much &fconfidence."
    - "&b%s &fwas betrayed by their own coordination."
    - "&b%s &fthought the ground was lava... and wasn't entirely wrong."
    - "&b%s &finvented a somersault and stayed in mortal."
    - "&b%s &ffell for the lies of the invisible platform."
    - "&b%s &fwanted to impress and only impressed the ground."
    - "&b%s &fshouted &a'I'm invincible!' &fjust before falling."
  kill-messages:
    - "&b%killer% &fhas sent &b%victim% &fon a one-way trip to the void!"
    - "&b%victim% &ftried to fly, but &b%killer% &fcut their wings."
    - "&b%killer% &fgave &b%victim% &fan epic push to the beyond!"
    - "&b%victim% &fthought they could, but &b%killer% &fsaid '&aNOPE, to the ground!'"
    - "&b%killer% &fturned &b%victim% &finto a shooting star... that didn't go far!"
    - "&b%victim% &fwanted to dance with &b%killer%&f, but ended up dancing with death."
    - "&b%killer% &ftaught &b%victim% &fthat gravity doesn't forgive!"
    - "&b%victim% &fdreamed of victory, but &b%killer% &fwoke them with a blow."
    - "&b%killer% &fsent &b%victim% &fto explore the bottom of the map!"
    - "&b%killer% &fgave &b%victim% &fan express ticket to the lobby of the fallen!"