main: mk.kvlzx.MysthicKnockBack
version: 1.0.0-SNAPSHOT
name: MysthicKnockBack
authors: [Kvlzx, Gabo]
api-version: 1.13
depend: [WorldEdit]

commands:
  mysthicknockback:
    description: Main command
    aliases: 
      - mk
      - kb
      - kbffa
  report:
    description: Command to report a player
    aliases:
      - report
  arena:
    description: Command to define an arena
  stats:
    description: Command to manage statistics
    aliases: [statistics]
  music:
    description: Open the music menu
  msg:
    description: Command to send a message to another player
    aliases: [message, tell]
  r:
    description: Command to reply to the last private message received
    aliases: [reply]
  socialspy:
    description: Command to toggle monitoring of private messages
  friend:
    description: Command to manage your friends list
    aliases: [amigo]
  friendaccept:
    description: Command to accept a friend request
    aliases: [friendaceptar]
  friendreject:
    description: Command to reject a friend request
    aliases: [friendrechazar]
  friendignore:
    description: Command to ignore a friend request
    aliases: [friendignorar]

permissions:
  staff.spy:
    description: Allows staff to view private messages
    default: op