main: mk.kvlzx.MysthicKnockBack
version: 1.0.0-SNAPSHOT
name: MysthicKnockBack
authors: [Kvlzx, Gabo]
api-version: 1.13
depend: [WorldEdit]

commands:
  mysthicknockback:
    description: Main command
    aliases: 
      - mk
      - kb
      - kbffa
  arena:
    description: Command to define an arena
  stats:
    description: Command to manage statistics
    aliases: [statistics]
  music:
    description: Open the music menu