menu:
  title: "&8• &e&lKill Sound Shop &8•"
  size: 54
  items:
    # Balance display
    balance:
      slot: 4
      material: EMERALD
      title: "&a&lYour Balance"
      lore:
        - "&7Current Balance: &e%balance% KGCoins"
    
    # Kill sound items configuration
    kill_sounds:
      slots: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53]
      title: "%rarity_color%%sound_name%"
      lore:
        - "%rarity_color%✦ Rarity: %rarity%"
        - ""
        - "%description%"
        - ""
        - "&eRight-click to preview"
        - ""
        - "%status_lore%"
      materials:
        common:
          selected: JUKEBOX
          unselected: NOTE_BLOCK
        epic:
          selected: JUKEBOX
          unselected: RECORD_11
        legendary:
          selected: JUKEBOX
          unselected: RECORD_12
      enchanted_if_selected: true
      hide_enchants: true
    
    # Back button
    back_button:
      slot: 49
      material: ARROW
      title: "&c← Back"
      lore:
        - "&7Click to return to the shop"
    
    # Filler items
    filler:
      material: STAINED_GLASS_PANE
      data: 7
      title: " "
      fill_empty_slots: true

# Kill sound definitions
kill_sound_items:
  # COMMON sounds
  victory_strike:
    name: "Victory Strike"
    sound: "LEVEL_UP"
    volume: 1.0
    pitch: 1.0
    price: 15000
    rarity: "COMMON"
    rarity_color: "&7"
    description: "&eThe sound of victory!"
  
  critical_hit:
    name: "Critical Hit"
    sound: "SUCCESSFUL_HIT"
    volume: 1.0
    pitch: 0.8
    price: 15000
    rarity: "COMMON"
    rarity_color: "&7"
    description: "&eCritical strike!"
  
  sword_clash:
    name: "Sword Clash"
    sound: "ANVIL_USE"
    volume: 0.8
    pitch: 1.2
    price: 15000
    rarity: "COMMON"
    rarity_color: "&7"
    description: "&7The clash of steel!"
  
  bow_shot:
    name: "Bow Shot"
    sound: "SHOOT_ARROW"
    volume: 1.0
    pitch: 1.0
    price: 15000
    rarity: "COMMON"
    rarity_color: "&7"
    description: "&7Perfect aim!"
  
  potion_splash:
    name: "Potion Splash"
    sound: "SPLASH2"
    volume: 1.0
    pitch: 1.0
    price: 15000
    rarity: "COMMON"
    rarity_color: "&7"
    description: "&7Alchemical victory!"

  # EPIC sounds
  blaze_fury:
    name: "Blaze Fury"
    sound: "BLAZE_DEATH"
    volume: 1.0
    pitch: 0.7
    price: 35000
    rarity: "EPIC"
    rarity_color: "&5"
    description: "&dThe fury of the blaze!"
  
  wither_strike:
    name: "Wither Strike"
    sound: "WITHER_HURT"
    volume: 0.8
    pitch: 1.0
    price: 35000
    rarity: "EPIC"
    rarity_color: "&5"
    description: "&dThe power of the wither!"
  
  enderman_teleport:
    name: "Enderman Teleport"
    sound: "ENDERMAN_TELEPORT"
    volume: 1.0
    pitch: 1.0
    price: 35000
    rarity: "EPIC"
    rarity_color: "&5"
    description: "&dVanished from existence!"
  
  ghast_cry:
    name: "Ghast Cry"
    sound: "GHAST_SCREAM"
    volume: 0.6
    pitch: 1.3
    price: 35000
    rarity: "EPIC"
    rarity_color: "&5"
    description: "&dThe cry of the netherworld!"

  # LEGENDARY sounds
  dragon_wrath:
    name: "Dragon Wrath"
    sound: "ENDERDRAGON_GROWL"
    volume: 1.0
    pitch: 0.5
    price: 75000
    rarity: "LEGENDARY"
    rarity_color: "&6"
    description: "&6The wrath of the dragon!"
  
  thunder_smite:
    name: "Thunder Smite"
    sound: "AMBIENCE_THUNDER"
    volume: 1.0
    pitch: 0.8
    price: 75000
    rarity: "LEGENDARY"
    rarity_color: "&6"
    description: "&6The fury of thunder!"
  
  explosive_victory:
    name: "Explosive Victory"
    sound: "EXPLODE"
    volume: 0.8
    pitch: 1.0
    price: 75000
    rarity: "LEGENDARY"
    rarity_color: "&6"
    description: "&6Explosive domination!"
  
  divine_bell:
    name: "Divine Bell"
    sound: "NOTE_PLING"
    volume: 1.0
    pitch: 2.0
    price: 75000
    rarity: "LEGENDARY"
    rarity_color: "&6"
    description: "&6The bell of victory!"
  
  phoenix_cry:
    name: "Phoenix Cry"
    sound: "ENDERDRAGON_WINGS"
    volume: 0.9
    pitch: 1.5
    price: 75000
    rarity: "LEGENDARY"
    rarity_color: "&6"
    description: "&6Rising from the ashes!"

# Status messages for different kill sound states
status_messages:
  owned_selected:
    - "&aCurrently selected"
    - "&8➥ Using this sound"
    - ""
    - "&eClick to deselect"
  
  owned_click_to_select:
    - "&eClick to select"
    - "&8➥ You already own this sound"
  
  purchasable:
    - "&7Click to purchase"
    - ""
    - "&8➥ Price: &e%price% KGCoins"
  
  insufficient_funds:
    - "&cInsufficient funds"
    - ""
    - "&8➥ Price: &e%price% KGCoins"
    - "&8➥ You have: &e%balance% KGCoins"

# Messages
messages:
  sound_selected: "&aYou have selected the sound: %sound_name%"
  sound_deselected: "&aYou have deselected the sound. Using no sound."
  sound_purchased: "&aYou have purchased and selected the sound %sound_name% &afor &e%price% KGCoins&a!"
  insufficient_funds: "&cYou don't have enough KGCoins to purchase this sound."