menu:
  title: "&8• &b&lMain Menu &8•"
  size: 45
  items:
    top-kills:
      id: DIAMOND_SWORD
      name: "&a&lTop Kills"
      lore:
        - "&7Click to view the top 10 kills"
      slot: 12
    top-elo:
      id: NETHER_STAR
      name: "&6&lTop ELO"
      lore:
        - "&7Click to view the top 10 ELO"
      slot: 13
    top-streaks:
      id: DIAMOND
      name: "&d&lTop Streaks"
      lore:
        - "&7Click to view the top 10 streaks"
      slot: 14
    top-kdr:
      id: GOLDEN_APPLE
      name: "&b&lTop KDR"
      lore: 
        - "&7Click to view the top 10 KDR"
      slot: 21
    top-time:
      id: WATCH
      name: "&e&lTop Time"
      lore:
        - "&7Click to view the top 10 playtime"  
      slot: 23
    edit-hotbar:
      id: DIAMOND_SWORD
      name: "&e&lEdit Hotbar"
      lore:
        - "&7Click to customize your hotbar"
        - ""
        - "&8➥ Customize the position of your items"
      slot: 37
    my-stats:
      id: PLAYER_SKULL # Material Custom of this item
      name: "&a&lMy Statistics"
      lore: 
      - "&7Click to view your statistics"
      slot: 39
    report-player: 
      id: BOOK_AND_QUILL
      name: "&c&lReport Player"
      lore: 
        - "&7Click to report a player"
        - ""
        - "&8➥ Report inappropriate behavior"
      slot: 41
    shop:
      id: EMERALD
      name: "&a&lShop"
      lore:
        - "&7Click to open the shop"
        - ""
        - "&8➥ Buy cosmetics and more!"
      slot: 43