
#----------------------------------------------------#
#               MysthicKnockback Reports             #
#                 Developed by Kvlzx                 #
#----------------------------------------------------#

player-list-menu:
  title: "&9Select a player to report"
  size: 54
  items:
    player:
      name: "&a%player_name%"
      material: "PLAYER_HEAD"
      lore:
        - "&7Click to report this player"
    previous-page:
      name: "&cPrevious Page"
      material: "ARROW"
      slot: 48
    next-page:
      name: "&aNext Page"
      material: "ARROW"
      slot: 50
    close-menu:
      name: "&cClose"
      material: "BARRIER"
      slot: 49

report-reason-menu:
  title: "&9Reporting %player_name%"
  size: 27
  items:
    close-menu:
      name: "&cClose"
      material: "BARRIER"
      slot: 26

reasons:
  - id: "HACKS"
    name: "&cHacks"
    material: "IRON_SWORD"
    lore:
      - "&7Reporting for hacks or cheats."
  - id: "CROSS_TEAM"
    name: "&cCross Team"
    material: "DIAMOND_SWORD"
    lore:
      - "&7Reporting for cross team."
  - id: "BUG_ABUSE"
    name: "&cBug Abuse"
    material: "TNT"
    lore:
      - "&7Reporting for bug abuse."
  - id: "CAMPING"
    name: "&cCamping"
    material: "LEATHER_BOOTS"
    lore:
      - "&7Reporting for camping."
